# Generated by Django 4.0.3 on 2022-06-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_note_note_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='contact',
        ),
    ]
